import concurrent.futures
import logging
import os
from typing import Any

import boto3
import pandas as pd
from dotenv import load_dotenv

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)


def load_environment() -> dict[str, str]:
    """
    Loads configuration from the .env file and prepares the output directory.

    Returns:
        dict[str, str]: A dictionary containing the loaded configuration parameters.
    """

    load_dotenv()

    config: dict[str, str] = {
        "endpoint_url": os.getenv("LOCALSTACK_ENDPOINT", "http://localhost:4566"),
        "region_name": os.getenv("AWS_REGION", "us-east-1"),
        "bucket_name": os.getenv("S3_BUCKET_NAME", "bike-data-2016-2020"),
        "output_dir": os.getenv("OUTPUT_DIRECTORY", "../data/tableau_data"),
    }

    os.makedirs(config["output_dir"], exist_ok=True)

    return config


def export_dynamodb_table(
    dynamodb_resource: Any, table_name: str, output_dir: str
) -> None:
    """
    Scans a DynamoDB table with pagination and saves the result locally as a CSV.

    Pagination ensures no data is lost if the table exceeds the 1MB scan limit.

    Args:
        dynamodb_resource (Any): The configured Boto3 DynamoDB resource.
        table_name (str): The name of the DynamoDB table to scan.
        output_dir (str): The local file path where the CSV will be saved.

    Returns:
        None
    """

    logger.info(f"Scanning DynamoDB table {table_name}...")
    table: Any = dynamodb_resource.Table(table_name)
    items: list[dict[str, Any]] = []

    try:
        response: dict[str, Any] = table.scan()
        items.extend(response.get("Items", []))

        while "LastEvaluatedKey" in response:
            response = table.scan(ExclusiveStartKey=response["LastEvaluatedKey"])
            items.extend(response.get("Items", []))

        if not items:
            logger.warning(f"Table {table_name} is empty.")
            return

        df = pd.DataFrame(items)
        df.to_csv(output_dir, index=False)
        logger.info(f"Successfully exported {len(df)} rows to {output_dir}")

    except Exception as e:
        logger.error(f"Failed to export table {table_name}: {e}")


def _download_single_s3_file(
    s3_client: Any, bucket_name: str, object_key: str, output_dir: str
) -> str:
    """
    Helper function to download a single file from S3 (used by the thread pool).

    Args:
        s3_client (Any): The configured Boto3 S3 client.
        bucket_name (str): The name of the S3 bucket.
        object_key (str): The S3 object key to download.
        output_dir (str): The local directory to save the downloaded file.

    Returns:
        str: The name of the downloaded file.
    """

    filename: str = object_key.split("/")[-1]
    local_path: str = os.path.join(output_dir, filename)

    s3_client.download_file(bucket_name, object_key, local_path)

    return filename


def export_s3_metrics(
    s3_client: Any, bucket_name: str, prefix: str, output_dir: str
) -> None:
    """
    Lists target objects in S3 and downloads them concurrently to maximize throughput.

    Args:
        s3_client (Any): The configured Boto3 S3 client.
        bucket_name (str): The name of the S3 bucket.
        prefix (str): The prefix to filter S3 objects by.
        output_dir (str): The local directory to save the downloaded files.

    Returns:
        None
    """

    logger.info(
        f"Listing objects in S3 bucket '{bucket_name}' with prefix '{prefix}'..."
    )
    try:
        response: dict[str, Any] = s3_client.list_objects_v2(
            Bucket=bucket_name, Prefix=prefix
        )
        objects: list[dict[str, Any]] = response.get("Contents", [])

        # Filter for the final CSV files generated by Spark
        keys_to_download: list[str] = [
            obj["Key"]
            for obj in objects
            if obj["Key"].endswith(".csv")
            and ("departures_" in obj["Key"] or "returns_" in obj["Key"])
        ]

        if not keys_to_download:
            logger.warning("No Spark CSV files found in S3.")
            return None

        logger.info(
            f"Found {len(keys_to_download)} files. Starting parallel download..."
        )

        # Use ThreadPoolExecutor for fast, concurrent network I/O
        download_count: int = 0

        with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
            # Map the helper function to the list of keys
            futures: dict[concurrent.futures.Future, str] = {
                executor.submit(
                    _download_single_s3_file, s3_client, bucket_name, key, output_dir
                ): key
                for key in keys_to_download
            }

            for future in concurrent.futures.as_completed(futures):
                try:
                    future.result()
                    download_count += 1
                except Exception as e:
                    logger.error(f"File download failed for {futures[future]}: {e}")

        logger.info(f"Successfully downloaded {download_count} Spark CSV files.")

    except Exception as e:
        logger.error(f"Failed to connect to S3: {e}")

    return None


def main() -> None:
    """Orchestrates the data extraction pipeline for Tableau visualization."""

    config: dict[str, str] = load_environment()

    # Initialize Boto3 Clients once and pass them down (Dependency Injection)
    boto_args: dict[str, str] = {
        "endpoint_url": config["endpoint_url"],
        "region_name": config["region_name"],
    }

    dynamodb_resource: Any = boto3.resource("dynamodb", **boto_args)
    s3_client: Any = boto3.client("s3", **boto_args)

    # 1. Execute DynamoDB Extractions
    export_dynamodb_table(
        dynamodb_resource=dynamodb_resource,
        table_name="BikeMetricsDaily",
        output_dir=os.path.join(config["output_dir"], "daily_metrics.csv"),
    )

    export_dynamodb_table(
        dynamodb_resource=dynamodb_resource,
        table_name="BikeMetricsMonthly",
        output_dir=os.path.join(config["output_dir"], "monthly_metrics.csv"),
    )

    # 2. Execute S3 Concurrent Extraction
    export_s3_metrics(
        s3_client=s3_client,
        bucket_name=config["bucket_name"],
        prefix="metrics/",
        output_dir=config["output_dir"],
    )

    logger.info("Pipeline extraction complete. Data is ready for Tableau.")

    return None


if __name__ == "__main__":
    main()
